# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.



Vagrant.configure(2) do |config|

  config.vm.box = "puphpet/ubuntu1404-x64"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 11223, host: 9001 #loadbalancer 
  config.vm.network "forwarded_port", guest: 17010, host: 9010 #server1 http
  config.vm.network "forwarded_port", guest: 17011, host: 9011 #server2 http
  config.vm.network "forwarded_port", guest: 8183,  host: 9000 #web admin

  #/vagrant is mapped to the directory contiaining the project by default
  config.vm.hostname = "zato"
  
  config.vm.provider "parallels" do |prl|
    prl.name = "my_vm"
    prl.memory = 1024
    prl.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
 
  #these are the right steps, but they seem to only work when copy pasted. idk 
  export ZATODIR=/opt/zatoenv

  #redis
  cd /vagrant
  sudo apt-get update
  sudo apt-get install linux-headers-$(uname -r) build-essential -y
  wget http://download.redis.io/redis-stable.tar.gz
  tar xvzf redis-stable.tar.gz
  cd redis-stable
  cd deps; make hiredis lua jemalloc linenoise geohash-int
  cd ..
  sudo make install
  cd utils
  sudo ./install_server.sh

  sudo service redis_6379 start
  cd /vagrant 

  #libxml
  sudo apt-get install libxml2 -y
  sudo apt-get install libxslt1.1 -y
  sudo apt-get install libxml2-dev -y
  sudo apt-get install libxslt1-dev -y
  sudo apt-get install python-libxml2 -y
  sudo apt-get install python-libxslt1 -y
  sudo apt-get install python-dev -y
  sudo apt-get install python-setuptools -y
  sudo easy_install lxml
  sudo apt-get install libffi-dev -y
  sudo easy_install -U setuptools

  sudo pip install --upgrade pip
  echo 'export PATH=$PATH:/usr/local/bin' >>~/.bash_profile
  PATH=$PATH:/usr/local/bin



  #zato
  sudo apt-get install curl -y
  sudo apt-get install python-software-properties -y
  curl -s https://zato.io/repo/zato-0CBD7F72.pgp.asc | sudo apt-key add -
  sudo apt-add-repository https://zato.io/repo/stable/2.0/ubuntu
  sudo apt-get update
  sudo apt-get -y install apt-transport-https
  sudo apt-get -y install zato
  export PATH=$PATH:/opt/zato/current/bin
  echo 'export PATH=$PATH:/opt/zato/current/bin' >>~/.bash_profile
  echo 'export ZATODIR='$ZATODIR >>~/.bash_profile
  zato --version
  sudo rm -rf $ZATODIR
  sudo mkdir $ZATODIR
  sudo chown vagrant $ZATODIR
  cd $ZATODIR
  zato quickstart create $ZATODIR sqlite localhost 6379  --verbose
  sudo find $ZATODIR | grep pid | xargs rm  
  find $ZATODIR/*.sh | xargs chmod a+x
  zato update password $ZATODIR/web-admin/ admin
  sudo pip install flake8
  pip install git+git://github.com/grenzi/zato-deploy-cli.git


  echo --------
  echo run: 
  echo 
  echo see here for changes to config for listenting: https://mailman-mail5.webfaction.com/pipermail/zato-discuss/2013-November/000102.html     gunicorn_bind=localhost:17010
  echo to clear a bad shutdown
  echo      find $ZATODIR | grep pid | xargs rm  
  echo to start zato
  echo      $ZATODIR/zato-qs-start.sh
  echo ping service
  echo      curl localhost:11223/zato/ping ; echo

  SHELL
end
